name: djamo_todo_tdd_test
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.24.3

# isar_version: &isar_version 3.1.0

dependencies:
  bloc: ^8.1.4
  cupertino_icons:
  dart_mappable: ^4.3.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  get_it: ^8.0.2
  go_router: ^14.6.1
  intl: ^0.19.0
  isar: 3.1.0
  isar_flutter_libs: 3.1.0
  path_provider: ^2.1.5

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.0
  flutter_test:
    sdk: flutter
  isar_generator: 3.1.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
